# Generated by Django 4.2.4 on 2023-09-08 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fusion_sync.utils
import s3_file_field.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FusionSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Resource ID')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='Filename (with extension)')),
                ('length', models.BigIntegerField(default=-1, verbose_name='Length (bytes)')),
                ('offset', models.BigIntegerField(default=0, verbose_name='Offset (bytes)')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadata (JSON)')),
                ('tmp_path', models.TextField(blank=True, verbose_name='Temporary path')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires at')),
                ('file', s3_file_field.fields.S3FileField(upload_to=fusion_sync.utils.get_upload_to, verbose_name='File (binary)')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='object id')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fusion_syncs', to='contenttypes.contenttype', verbose_name='content type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fusion_syncs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Fusion Sync',
                'verbose_name_plural': 'Fusion Syncs',
                'db_table': 'fusion_sync',
            },
        ),
    ]
