# Generated by Django 4.2.4 on 2023-09-02 04:42

from django.db import migrations
import fusion_sync.utils
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_sync', '0002_alter_fusionsync_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fusionsync',
            name='file',
            field=s3_file_field.fields.S3FileField(upload_to=fusion_sync.utils.get_upload_to, verbose_name='File (binary)'),
        ),
    ]
